routes/web.php
<?php

use App\Enums\RoleEnum;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Guest\Game\GameController;
use App\Http\Controllers\Guest\Game\OnlineGameController;
use App\Http\Controllers\Guest\HomeController;
use App\Http\Controllers\Guest\Show\MovieController;
use App\Http\Controllers\Guest\Show\SeriesController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::group([
    'middleware' => ['auth','checkRole:' . RoleEnum::ADMIN->value],
], function () {

    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

});

 Route::get('/home', [HomeController::class, 'index'])->name('home');


Route::group([
    "prefix" => 'user',
], function () {
    require __DIR__ . '/user/main.php';
});

require __DIR__ . '/auth.php';

Route::group([
    "prefix" => 'user',
    "middleware" => ['auth','checkRole:' . RoleEnum::ADMIN->value . '|' . RoleEnum::USER->value]
], function () {
    require __DIR__ . '/user/user.php';
});
Route::group([
    "prefix" => 'admin',
    "middleware" => ['auth','checkRole:' . RoleEnum::ADMIN->value]
], function () {
    require __DIR__ . '/admin/admin.php';
});

app/Models/Show.php
<?php

namespace App\Models;

use App\Enums\ShowTypeEnum;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Maize\Markable\Markable;
use Maize\Markable\Models\Like;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\Support\MediaStream;


class Show extends Model implements HasMedia
{
    use HasFactory;
    use InteractsWithMedia;
    // use Markable;


    // protected static $marks = [
    //     Like::class,
    // ];



    protected $casts = [];

    protected $guarded = [];

    protected $attributes = [
        "view_count" => 0,
    ];

    ########## Relations ##########


    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    public function teamMembers(): BelongsToMany
    {
        return $this->belongsToMany(TeamMember::class);
    }

    public function rates(): HasMany
    {
        return $this->hasMany(Rate::class);
    }

    public function comments(): hasMany
    {
        return $this->hasMany(Comment::class);
    }
    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class,'buys')
        ->withPivot('price')
        ->withTimestamps();
    }
    public function processMedia()
    {
        $media = collect();
        foreach ($this->episodes as $episode) {
            $media = $media->merge($episode->getMedia('Episode'));
        }

        return MediaStream::create('episodes.zip')->addMedia($media);
    }


    public function episodes(): HasMany
    {
        return $this->hasMany(Episode::class);
    }

    public function getAverageRatingAttribute()
    {
        return $this->rates()->avg('value');
    }

    // protected function likeCount(): Attribute
    // {
    //     return Attribute::make(
    //         get: fn() => Like::count($this)
    //     );
    // }





    ########## Libraries ##########

    public function scopeMovie($query)
    {
        return $query->where('show_type', ShowTypeEnum::MOVIE->value);
    }

    public function scopeSeries($query)
    {
        return $query->where('show_type', ShowTypeEnum::SERIES->value);
    }

    public function scopeMinRate($query, $minRate)
    {
        return $query->whereHas('rates', function ($q) use ($minRate) {
            $q->selectRaw('AVG(value)')->havingRaw('AVG(value) >= ?', [$minRate]);
        });
    }


    public function scopeMaxRate($query, $maxRate)
    {
        return $query->whereHas('rates', function ($q) use ($maxRate) {
            $q->selectRaw('AVG(value)')->havingRaw('AVG(value) <= ?', [$maxRate]);
        });
    }

 public function registerMediaCollections(): void
    {
        $this
            ->addMediaCollection('ShowImage')
            ->useFallbackUrl(config('app.url') . '/images/default.jpg')
            ->singleFile();

        $this
            ->addMediaCollection('ShowPromo')
            ->useFallbackUrl(config('app.url') . '/images/default.jpg')
            ->singleFile();

        $this
            ->addMediaCollection('ShowFile')
            ->useFallbackUrl(config('app.url') . '/images/default.jpg')
            ->singleFile();
    }


}

app/Http/Controllers/Dashboard/Show/SeriesController.php
<?php

namespace App\Http\Controllers\Dashboard\Show;

use App\Enums\ShowTypeEnum;
use App\Enums\ShowYearEnum;
use App\Http\Controllers\Controller;
use App\Models\Show;
use App\Http\Requests\Dashboard\Series\StoreSeriesRequest;
use App\Http\Requests\Dashboard\Series\UpdateSeriesRequest;
use App\Models\Category;
use App\Models\Setting;
use App\Models\TeamMember;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use Spatie\QueryBuilder\QueryBuilder;

class SeriesController extends Controller
{

    public function index(): View
    {
        $serieses = QueryBuilder::for(Show::series())
        ->with(['category', 'teamMembers'])
        ->allowedFilters('show_name')
        ->latest('id')
        ->get();
        return view(
            'dashboard.pages.series.index',
            compact('serieses')
        );
    }


    public function create(): View
    {
        $years = ShowYearEnum::getTypesForSelect();

        $teamMembers = TeamMember::all();
        $categories = Category::all();
        $show_types = ShowTypeEnum::getTypesForSelect();

        return view(
            'dashboard.pages.series.create',
            compact(['categories', 'show_types', 'teamMembers', 'years'])
        );
    }


    public function store(StoreSeriesRequest $request): RedirectResponse
    {
        // Store Show
        $points = Setting::getPoints($request->price);
        $show = Show::create([
            ...$request->validated(),
            'points' => $points
        ]);
        $show->teamMembers()->sync($request->team_members);


        // Add media to Show
        $show
            ->addMediaFromRequest('image')
            ->toMediaCollection('ShowImage');

        $show
            ->addMediaFromRequest('promo')
            ->toMediaCollection('ShowPromo');


        return redirect()->route('series.index');
    }


    public function edit(Show $show): View
    {
        $years = ShowYearEnum::getTypesForSelect();

        $categories = Category::all();
        $teamMembers = TeamMember::all();

        $show_types = ShowTypeEnum::getTypesForSelect();

        return view(
            'dashboard.pages.series.edit',
            compact(['show', 'categories', 'show_types', 'teamMembers', 'years'])
        );
    }


    public function update(UpdateSeriesRequest $request, Show $show): RedirectResponse
    {
        $points = $show->price != $request->price ?
        Setting::getPoints($request->price) : $show->points;
        // Update Show
        $show->update([
            ...$request->validated(),
            'points' => $points
        ]);

        $show->teamMembers()->sync($request->team_members);
        // Edit Image for  Show if exist
        $request->hasFile('image') &&
            $show
            ->addMediaFromRequest('image')
            ->toMediaCollection('ShowImage');

        $request->hasFile('file') &&
            $show
            ->addMediaFromRequest('file')
            ->toMediaCollection('ShowFile');

        $request->hasFile('promo') &&
            $show
            ->addMediaFromRequest('promo')
            ->toMediaCollection('ShowPromo');

            return redirect()->route('series.index');
        }


    public function destroy(Show $show): RedirectResponse
    {
        // Delete Show
        $show->delete();

        return back();
    }
}

app/Http/Controllers/Guest/Show/SeriesController.php
<?php

namespace App\Http\Controllers\Guest\Show;

use App\Actions\GetCategoriesDependsOnBirth;
use App\Enums\ShowTypeEnum;
use App\Enums\ShowYearEnum;
use App\Http\Controllers\Controller;
use App\Models\Show;
use App\Http\Requests\Dashboard\Series\StoreSeriesRequest;
use App\Http\Requests\Dashboard\Series\UpdateSeriesRequest;
use App\Models\Category;
use App\Models\TeamMember;
use App\Services\ShowService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;
use Spatie\MediaLibrary\Support\MediaStream;
use Spatie\QueryBuilder\AllowedFilter;
use Spatie\QueryBuilder\QueryBuilder;

class SeriesController extends Controller
{

    public function index(Request $request): View
    {
        // dd($request->all());
        $categories = (new GetCategoriesDependsOnBirth)->handle();
        $serieses = QueryBuilder::for(Show::series())
            ->whereHas('category', function ($q) use ($categories) {
                $q->whereIn('id', $categories->pluck('id')->toArray());
            })
            ->with(['category', 'rates'])
            ->allowedFilters([
                AllowedFilter::exact('category_id'),
                AllowedFilter::exact('release_date'),
                AllowedFilter::scope('min_rate')->ignore(0),
                AllowedFilter::scope('max_rate')->ignore(10),
                'show_name'
            ])
            ->latest('id')
            ->paginate(5)
            ->appends(request()->query());
        $years = ShowYearEnum::getTypesForSelect();

        return view('guest.pages.series.index', compact(['serieses', 'categories', 'years']));
    }


    public function show(Show $show): View
    {
        $show->increment('view_count');


        $comments = $show->comments()
            ->where('parent_id', null)
            ->with('replies.user')
            ->latest('id')
            ->get();
        $rates = $show->rates()
            ->with('user')
            ->latest('id')
            ->get();

        return view(
            'guest.pages.series.show',
            compact(['show', 'comments', 'rates'])
        );
    }

    public function download(Show $show)
    {
        // (new ShowService)->attach($show,$user);
        //  return (new ShowService)->download($show,$user);

        $user = Auth::user();
        $user->shows()->syncWithoutDetaching([$show->id => ['price' => $show->price]]);
        $user->decrement('points', $show->points);

        $media = collect();
        foreach ($show->episodes as $episode) {
            $media = $media->merge($episode->getMedia('Episode'));
        }

        return MediaStream::create($show->show_name . '.zip')->addMedia($media);
    }
}

resources/views/guest/pages/series/index.blade.php
<x-guest-layout::guest-layout>
    <x-slot name="title">
        Series
    </x-slot>
    <x-slot name="head">
        <style>
            .filter-select {
                -webkit-box-shadow: 0 5px 25px 0 rgba(0, 0, 0, 0.3);
                background-color: #2b2b31;
                box-shadow: 0 5px 25px 0 rgba(0, 0, 0, 0.3);
                /* Change the background color */
                color: #343a40;
                /* Change the text color */
                /* border: 1px solid #ced4da; */
                /* Change the border color */
                border-radius: 0.25rem;
                /* Change the border radius */
                padding: 0.375rem 0.75rem;
                /* Change the padding */
                font-size: 1rem;
                color: #fff;
                font-family: Arial, sans-serif;

            }

            .filter-select>option {
                display: block;
                line-height: 40px;
                font-size: 14px;
                color: rgba(255, 255, 255, 0.75);
                position: relative;
                font-weight: 300;
                cursor: pointer;
                -webkit-transition: 0.4s ease;
                -moz-transition: 0.4s ease;
                transition: 0.4s ease;
            }

            .filter-select>option:hover {
                color: #ff55a5;

            }

            .custom-select option {
                background-color: #ffffff;
                /* Change the background color of options */
                color: #495057;
                /* Change the text color of options */
            }

            .custom-select option:hover {
                background-color: #e9ecef;
                /* Hover background color */
                color: #007bff;
                /* Hover text color */
            }

            .custom-select option:checked {
                background-color: #007bff;
                /* Change the background color of selected option */
                color: #ffffff;
                /* Change the text color of selected option */
            }

            .custom-select::after {
                content: "▼";
                position: absolute;
                right: 1rem;
                pointer-events: none;
                color: #495057;
            }
        </style>
    </x-slot>
   	<!-- page title -->
	<section class="section section--first section--bg" data-bg={{asset('guest/assets/img/section/section.jpg')}}>
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="section__wrap">
						<!-- section title -->
						<h2 class="section__title">TV Series</h2>
						<!-- end section title -->

						<!-- breadcrumb -->
						<ul class="breadcrumb">
                            <li class="breadcrumb__item"><a href={{route('home')}}>Home</a></li>
                            <li class="breadcrumb__item breadcrumb__item--active">TV Series</li>
						</ul>
						<!-- end breadcrumb -->
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end page title -->

    <div class="filter">
        <div class="container">
            <div class="row">

                <div class="col-12">
                    <form action="{{ route('user.series.index') }}" method="get">


                        <div class="filter__content">
                            <div class="filter__items">
                                <div class="filter__item" id="filter__genre">
                                    <span class="filter__item-label">GENRE:</span>

                                    <select class="filter-select" class="form-select form-select-sm mb-3" required=""
                                        aria-label="s.form-select-sm example" name="filter[category_id]">
                                        <option selected disabled>Select Genre</option>
                                        @foreach ($categories as $category)
                                            <option @selected(request()->input('filter.category_id') == $category->id) value="{{ $category->id }}">{{ $category->category_type }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <!-- filter item -->
                                <div class="filter__item" id="filter__year">
                                    <span class="filter__item-label">RELEASE YEAR:</span>
                                    <select class="filter-select" style="" class="form-select form-select-sm mb-5"
                                        required="" aria-label="s.form-select-sm example" name="filter[release_date]">
                                        <option selected disabled>Select Year</option>
                                        @foreach ($years as $key => $year)
                                            <option @selected(request()->input('filter.release_date') == $key) value="{{ $key }}">
                                                {{ $year }}</option>
                                        @endforeach
                                    </select>

                                </div>
                                <!-- end filter item -->
                                  <!-- end filter item -->
                                  <div class="filter__item" id="filter__rate">
                                    <span class="filter__item-label"> RATE:</span>

                                      <div class="filter__item-btn dropdown-toggle" role="button" id="filter-rate"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <div class="filter__range">
                                            <div id="filter__imbd-start">{{ request()->input('filter.min_rate') }}</div>
                                            <div id="filter__imbd-end">{{ request()->input('filter.max_rate') }}</div>
                                            <input hidden name="filter[min_rate]" value="{{ request()->input('filter.min_rate') }}" id="min_rate">
                                            <input hidden name="filter[max_rate]" value="{{ request()->input('filter.max_rate') }}" id="max_rate">
                                        </div>
                                        <span></span>
                                    </div>

                                    <div class="filter__item-menu filter__item-menu--range dropdown-menu"
                                        aria-labelledby="filter-rate">
                                        <div id="filter__imbd"></div>
                                    </div>

                                </div>
                                <!-- filter item -->
                                <div class="filter__item" id="filter_name">
                                    <span class="filter__item-label">Series NAME:</span>
                                    <input value="{{request()->input('filter.show_name')}}" name="filter[show_name]" type="text" class="sign__input" placeholder="Series1:ex" >
                                </div>
                                <!-- end filter item -->


                            </div>

                            <!-- filter btn -->
                            <button class="filter__btn" type="submit">apply filter</button>
                            <!-- end filter btn -->

                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>


	<!-- catalog -->
	<div class="catalog">
		<div class="container">
			<div class="row">
                @foreach ($serieses as $series)
                <!-- card -->
                <div class="col-6 col-sm-4 col-lg-3 col-xl-2">
                    <div class="card">
                        <div class="card__cover">
                            <img style="background-size: cover;
                        object-fit: cover;
                        width: 200px
                        height: 300px
                        aspect-ratio: 3/4;
                        aspect-ratio: 3/4;"
                                src="{{ $series->getFirstMediaUrl('ShowImage') }}" alt="">
                            <a href="{{ route('user.series.show', $series->id) }}" class="card__play">
                                <i class="icon ion-ios-play"></i>
                            </a>
                        </div>
                        <div class="card__content">
                            <h3 class="card__title"><a href="#">{{ $series->show_name }}</a></h3>
                            <span class="card__category">
                                <a href="#">{{ $series->category->category_type }}</a>
                            </span>
                            <span class="card__rate"><i
                                    class="icon ion-ios-star"></i>{{ number_format($series->average_rating, 2) }}</span>
                        </div>
                    </div>
                </div>
                <!-- end card -->
            @endforeach
				<!-- paginator -->
                {{ $serieses->links('vendor.pagination.custom') }}

				<!-- end paginator -->
			</div>
		</div>
	</div>
	<!-- end catalog -->


</x-guest-layout::guest-layout>